apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - networkpolicies/tradenest-prod.yaml
  - networkpolicies/tradenest-staging.yaml
  - podsecurity/namespaces.yaml
  - kyverno/policies.yaml
  - sealedsecrets/sealedsecrets.yaml
  - waf/ingress-nginx-waf.yaml
  - tls/clusterissuers.yaml
  - tls/certificates.yaml
  - audit/audit-policy.yaml

commonLabels:
  app.kubernetes.io/part-of: tradenest-security
  app.kubernetes.io/managed-by: kustomize