apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tradenest-secrets
  namespace: tradenest-prod
spec:
  encryptedData:
    database-url: "AgBy...=="
    redis-url: "AgBy...=="
    jwt-secret: "AgBy...=="
    jwt-refresh-secret: "AgBy...=="
    razorpay-key-id: "AgBy...=="
    razorpay-key-secret: "AgBy...=="
    stripe-secret-key: "AgBy...=="
    smtp-host: "AgBy...=="
    smtp-port: "AgBy...=="
    smtp-user: "AgBy...=="
    smtp-pass: "AgBy...=="
  template:
    metadata:
      name: tradenest-secrets
      namespace: tradenest-prod
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tradenest-secrets
  namespace: tradenest-staging
spec:
  encryptedData:
    database-url: "AgBy...=="
    redis-url: "AgBy...=="
    jwt-secret: "AgBy...=="
    jwt-refresh-secret: "AgBy...=="
    razorpay-key-id: "AgBy...=="
    razorpay-key-secret: "AgBy...=="
    stripe-secret-key: "AgBy...=="
    smtp-host: "AgBy...=="
    smtp-port: "AgBy...=="
    smtp-user: "AgBy...=="
    smtp-pass: "AgBy...=="
  template:
    metadata:
      name: tradenest-secrets
      namespace: tradenest-staging
    type: Opaque