apiVersion: v1
kind: ConfigMap
metadata:
  name: common-labels
  namespace: tradenest
data:
  app.kubernetes.io/name: "tradenest"
  app.kubernetes.io/part-of: "tradenest-platform"
  app.kubernetes.io/managed-by: "kustomize"