apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tradenest

resources:
  - namespace.yaml
  - common-labels.yaml

commonLabels:
  app.kubernetes.io/name: tradenest
  app.kubernetes.io/part-of: tradenest-platform